# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: 'kubectl-openebs'

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
  - main: './cmd/pwa-server/main.go'
      goos: [ 'linux', 'darwin', 'windows' ]
      goarch: [ '386', 'amd64', 'arm32', 'arm64' ]
      env:
        - CGO_ENABLED=0

archives:
  - name_template: '{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: 'windows'
        format: 'zip'
    wrap_in_directory: true
    files:
      - README.md
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: x86_32
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
