name: Release Go Binaries

on: 
  release:
    types: [created]
  workflow_dispatch:

env:
  CMD_PATH: ./


jobs:
  releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          # windows/386 and darwin/386 seems useless 
          - goarch: "386"
            goos: windows 
          - goarch: "386"
            goos: darwin 
    steps:
    - uses: actions/checkout@v2

    - name: Set APP_VERSION env
      run: echo APP_VERSION=$(echo hello)
      
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0

    - uses: wangyoucao577/go-release-action@v1.16
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: "${{ env.CMD_PATH }}"
        build_flags: -v
